### ISSUE TITLE
Batch register expects URL

### ISSUE THREAD

**Issue by david4096** [ini-bdds/minid#31]
The format of the manifest in the documentation doesn't have `url` in it. Trying to register a manifest using that JSON throws this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/minid", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/minid_client/minid.py", line 145, in main
    _main()
  File "/usr/local/lib/python2.7/dist-packages/minid_client/minid.py", line 77, in _main
    args.globus_auth_token)
  File "/usr/local/lib/python2.7/dist-packages/minid_client/minid_client_api.py", line 188, in register_entities
    url = entity['url']
KeyError: 'url'
```
Python 2.7.12+ 
minid version 1.2.3

**Comment by kylechard** [comment]
I've updated the readme file and tested that it works.

**Comment by david4096** [comment]
Thanks, I was able to work around it by adding the url as the README now describes.

For what it's worth, I'm working on a document to help folks figure out how to use GUIDs with minids as the example! https://github.com/DataBiosphere/identifier-interoperability
https://github.com/DataBiosphere/identifier-interoperability/pull/20
